Repository Leap-MERN-2023/cinema-app, pull requests merged in 2024-04, with the labels that each got.

#125 116 ticket etc responsive
  front-app/src/components/app/event/data.ts
  front-app/src/components/app/event/dialog.tsx
  front-app/src/components/app/event/eventSection.tsx
  front-app/src/components/app/event/index.tsx
  front-app/src/components/footer/index.tsx
  front-app/src/components/movieCard/index.tsx
  front-app/src/components/ui/dialog.tsx
Labels: enhancement

#126 zassan323232
  backend-app/data/film.json
  backend-app/src/model/movie.ts
  front-app/src/components/app/orderPage/cinema/cinemaButton.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/carousel/dialog.tsx
  front-app/src/components/carousel/resizeImage.tsx
  front-app/src/components/contexts/movie.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/movieCard/index.tsx
Labels: bug

#127 tasalbar uusdeg bolov
  backend-app/src/controller/order.ts
  backend-app/src/controller/ticket.ts
  backend-app/src/middleware/auth.ts
  backend-app/src/model/ticket.ts
  backend-app/src/router/ticket.ts
  front-app/src/components/app/orderPage/cinema/cinemaButton.tsx
  front-app/src/components/app/orderPage/cinema/cinemaSection.tsx
  front-app/src/components/app/orderPage/cinema/index.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/app/orderPage/order-steps/choose-cinema.tsx
  front-app/src/components/app/orderPage/order-steps/choose-sits.tsx
  front-app/src/components/app/orderPage/order-steps/confirmation.tsx
  front-app/src/components/app/orderPage/order-steps/index.ts
  front-app/src/components/app/orderPage/order-steps/qr-code.tsx
  front-app/src/components/app/orderPage/orderParts/index.tsx
  front-app/src/components/app/orderPage/orderParts/seats.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/cinema.tsx
  front-app/src/components/contexts/showtime.tsx
  front-app/src/components/movieCard/index.tsx
Labels: enhancement, context

#129 ticketPrice
  backend-app/data/film.json
  backend-app/src/model/movie.ts
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/movieCard/dialog.tsx
Labels: enhancement

#130 ui changes
  front-app/src/components/app/orderPage/cinema/cinemaButton.tsx
  front-app/src/components/app/orderPage/order-steps/choose-cinema.tsx
  front-app/src/components/app/orderPage/order-steps/choose-sits.tsx
  front-app/src/components/app/orderPage/order-steps/confirmation.tsx
Labels: enhancement

#133 coming soon page done
  backend-app/data/comingsoon.json
  backend-app/data/film.json
  backend-app/package.json
  backend-app/src/controller/comingsoon.ts
  backend-app/src/index.ts
  backend-app/src/model/comingsoon.ts
  backend-app/src/router/comingsoon.ts
  backend-app/src/utils/comingsoon.ts
  front-app/src/app/layout.tsx
  front-app/src/components/app/comingsoon/cardSection.tsx
  front-app/src/components/app/comingsoon/cards.tsx
  front-app/src/components/app/comingsoon/comingModal.tsx
  front-app/src/components/app/comingsoon/index.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/carousel/dialog.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/cinema.tsx
  front-app/src/components/contexts/comingsoon.tsx
  front-app/src/components/contexts/index.ts
  front-app/src/components/contexts/movie.tsx
  front-app/src/components/contexts/order.tsx
  front-app/src/components/contexts/screen.tsx
  front-app/src/components/contexts/showtime.tsx
  front-app/src/components/movieCard/index.tsx
Labels: controller, context

#134 123 frontend filter
  front-app/src/components/contexts/movie.tsx
  front-app/src/components/ui/select-filter.tsx
Labels: bug

#139 admin movie card
  admin-app/app/calendar/page.tsx
  admin-app/app/globals.css
  admin-app/app/layout.tsx
  admin-app/app/movies/page.tsx
  admin-app/components/Calender/index.tsx
  admin-app/components/Movies/index.tsx
  admin-app/components/Movies/movie-card.tsx
  admin-app/components/Sidebar/Sidebar.tsx
  admin-app/package-lock.json
  admin-app/package.json
Labels: component

#142 137 admin cinema
  admin-app/app/cinema/page.tsx
  admin-app/components/Breadcrumbs/Breadcrumb.tsx
  admin-app/components/Cinema/index.tsx
  admin-app/components/Sidebar/Sidebar.tsx
Labels: component

#149 ticket ordertoi holbloo
  backend-app/src/controller/customer.ts
  backend-app/src/controller/order.ts
  backend-app/src/controller/ticket.ts
  backend-app/src/model/customer.ts
  backend-app/src/model/order.ts
  backend-app/src/router/order.ts
  front-app/package.json
  front-app/src/app/layout.tsx
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/order.tsx
  front-app/src/components/contexts/showtime.tsx
Labels: enhancement

#151 event nemj duuslaa
  admin-app/app/events/page.tsx
  admin-app/app/layout.tsx
  admin-app/components/Movies/index.tsx
  admin-app/components/Sidebar/Sidebar.tsx
  admin-app/components/context/event.tsx
  admin-app/components/context/index.ts
  admin-app/components/event/dialog/dialog-file.tsx
  admin-app/components/event/dialog/dialog-text.tsx
  admin-app/components/event/dialog/event-dialog.tsx
  admin-app/components/event/event-card.tsx
  admin-app/components/event/index.tsx
  admin-app/components/index.ts
  admin-app/types/event.ts
  backend-app/data/event.json
  backend-app/package.json
  backend-app/src/controller/event.ts
  backend-app/src/index.ts
  backend-app/src/model/event.ts
  backend-app/src/router/event.ts
  backend-app/src/utils/event.ts
  front-app/src/app/layout.tsx
  front-app/src/components/app/event/data.ts
  front-app/src/components/app/event/eventSection.tsx
  front-app/src/components/contexts/event.tsx
  front-app/src/components/contexts/index.ts
  front-app/src/components/index.ts
  front-app/src/components/types/event.ts
  front-app/src/components/types/index.ts
Labels: component, controller, context

#157 146 final respo
  front-app/src/app/comingsoon/page.tsx
  front-app/src/app/event/page.tsx
  front-app/src/components/app/comingsoon/cardSection.tsx
  front-app/src/components/app/comingsoon/comingModal.tsx
  front-app/src/components/app/comingsoon/index.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/app/event/dialog.tsx
  front-app/src/components/app/event/eventSection.tsx
  front-app/src/components/app/event/index.tsx
  front-app/src/components/carousel/dialog.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/carousel/trailerModal.tsx
  front-app/src/components/header/altProfileDrawer.tsx
  front-app/src/components/header/drawer.tsx
  front-app/src/components/header/index.tsx
  front-app/src/components/movieCard/card.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/movieCard/index.tsx
  front-app/src/components/profileDrawer/login.tsx
  front-app/src/components/profileDrawer/signup.tsx
  front-app/src/components/ui/select-filter.tsx
  front-app/src/components/ui/sheet.tsx
Labels: enhancement

#161 bug fixes
  backend-app/src/controller/auth.ts
  backend-app/src/controller/customer.ts
  backend-app/src/index.ts
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/event.tsx
  front-app/src/components/profileDrawer/signup.tsx
Labels: bug

#165 164 admin login
  admin-app/app/chart/page.tsx
  admin-app/app/layout.tsx
  admin-app/app/profile/page.tsx
  admin-app/app/settings/page.tsx
  admin-app/app/signin/page.tsx
  admin-app/app/tables/page.tsx
  admin-app/components/Header/DropdownUser.tsx
  admin-app/components/Header/index.tsx
  admin-app/components/Sidebar/Sidebar.tsx
  admin-app/components/context/auth.tsx
  admin-app/components/context/index.ts
  admin-app/components/utils/axios.ts
  admin-app/package.json
  backend-app/src/controller/customer.ts
  backend-app/src/index.ts
Labels: component, context

#169 admin userlist duusav
  admin-app/app/chart/page.tsx
  admin-app/app/tables/page.tsx
  admin-app/components/Tables/TableTwo.tsx
  admin-app/context/auth.tsx
  backend-app/src/controller/customer.ts
  backend-app/src/router/user.ts
Labels: component

#170 162 showtime request
  backend-app/src/controller/order.ts
  backend-app/src/controller/showtime.ts
  backend-app/src/router/showtime.ts
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/cinema/cinemaSection.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/order.tsx
  front-app/src/components/contexts/showtime.tsx
  front-app/src/components/movieCard/card.tsx
  front-app/src/components/movieCard/dialog.tsx
Labels: component

#171 162 showtime request
  backend-app/src/controller/showtime.ts
  backend-app/src/router/showtime.ts
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/order.tsx
  front-app/src/components/contexts/showtime.tsx
Labels: component, controller, context

#175 done
  front-app/src/app/ticket/page.tsx
  front-app/src/components/app/comingsoon/index.tsx
  front-app/src/components/app/event/dialog.tsx
  front-app/src/components/app/event/index.tsx
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/cinema/cinemaButton.tsx
  front-app/src/components/app/orderPage/cinema/cinemaSection.tsx
  front-app/src/components/app/orderPage/cinema/index.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/app/orderPage/order-steps/choose-cinema.tsx
  front-app/src/components/app/orderPage/order-steps/choose-sits.tsx
  front-app/src/components/app/orderPage/order-steps/confirmation.tsx
  front-app/src/components/app/orderPage/order-steps/qr-code.tsx
  front-app/src/components/app/orderPage/paymentQr/index.tsx
  front-app/src/components/app/ticketpage/index.tsx
  front-app/src/components/footer/index.tsx
  front-app/src/components/header/drawer.tsx
  front-app/src/components/ticket/dialog.tsx
  front-app/src/components/ticket/index.tsx
Labels: enhancement

#179 updateeee
  backend-app/src/controller/showtime.ts
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/cinema/cinemaSection.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/movie.tsx
  front-app/src/components/movieCard/dialog.tsx
Labels: enhancement, component, controller, controllerChange, context

#180 ticket zasasj duusav
  backend-app/src/controller/auth.ts
  backend-app/src/controller/customer.ts
  front-app/src/components/app/ticketpage/index.tsx
  front-app/src/components/app/ticketpage/ticket/dialog.tsx
  front-app/src/components/app/ticketpage/ticket/index.tsx
  front-app/src/components/ticket/dialog.tsx
Labels: component

#186 delete render bolon busad zuils zasav
  admin-app/app/settings/page.tsx
  admin-app/components/Header/DropdownUser.tsx
  admin-app/context/auth.tsx
  admin-app/context/passwordrecover.tsx
  backend-app/src/controller/customer.ts
  backend-app/src/router/user.ts
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/app/ticketpage/index.tsx
  front-app/src/components/app/ticketpage/ticket/dialog.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/order.tsx
  front-app/src/components/contexts/passwordrecover.tsx
  front-app/src/components/ui/select-filter.tsx
Labels: bug, controller, context

#188 172 admin showtime
  admin-app/app/layout.tsx
  admin-app/app/showtime/page.tsx
  admin-app/components/Showtime/dialog-text.tsx
  admin-app/components/Showtime/index.tsx
  admin-app/components/Showtime/modal.tsx
  admin-app/components/Sidebar/Sidebar.tsx
  admin-app/components/index.ts
  admin-app/components/utils/input-field/index.tsx
  admin-app/context/cinema.tsx
  admin-app/context/index.ts
  admin-app/context/showtime.tsx
  admin-app/types/cinema.ts
  admin-app/types/event.ts
  backend-app/src/controller/event.ts
  backend-app/src/controller/showtime.ts
  backend-app/src/model/screen.ts
  backend-app/src/model/showtime.ts
  backend-app/src/router/showtime.ts
  front-app/src/app/layout.tsx
  front-app/src/common/loader.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/header/drawer.tsx
  front-app/src/components/movieCard/dialog.tsx
Labels: bug, enhancement, component, controller, context

#190 fix
  admin-app/components/Showtime/dialog-text.tsx
  admin-app/components/Showtime/index.tsx
  admin-app/components/Sidebar/Sidebar.tsx
  backend-app/src/controller/showtime.ts
  backend-app/src/router/showtime.ts
Labels: bug

#193 all respo is done(?)
  admin-app/app/profile/page.tsx
  admin-app/components/Cinema/CinemaCard.tsx
  admin-app/components/Cinema/index.tsx
  admin-app/components/Header/index.tsx
  admin-app/components/Movies/coming-soon/edit/dialog-text.tsx
  admin-app/components/Movies/coming-soon/edit/edit-dialog.tsx
  admin-app/components/Movies/coming-soon/index.tsx
  admin-app/components/Movies/coming-soon/movie-card.tsx
  admin-app/components/Movies/coming-soon/trailer-dailog.tsx
  admin-app/components/Movies/movies/edit/dialog-text.tsx
  admin-app/components/Movies/movies/edit/edit-dialog.tsx
  admin-app/components/Movies/movies/index.tsx
  admin-app/components/Movies/movies/movie-card.tsx
  admin-app/components/Movies/movies/trailer-dailog.tsx
  admin-app/components/Showtime/dialog-text.tsx
  admin-app/components/Showtime/index.tsx
  admin-app/components/Sidebar/ExpandMenu.tsx
  admin-app/components/Sidebar/MenuItem.tsx
  admin-app/components/Sidebar/Sidebar.tsx
  admin-app/components/event/edit/edit-dialog.tsx
  admin-app/components/event/event-card.tsx
  admin-app/components/event/index.tsx
  front-app/src/app/not-found.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/orderParts/seats.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/ui/select-filter.tsx
Labels: enhancement

#195 gyls
  backend-app/src/config/passport.ts
  backend-app/src/controller/auth.ts
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
Labels: bug

#196 context fcuk
  admin-app/components/Cinema/CinemaCard.tsx
  admin-app/components/Cinema/CinemaPut.tsx
  admin-app/components/Cinema/DeleteCinema.tsx
  admin-app/components/Cinema/cinemaBranch.tsx
  admin-app/components/Cinema/index.tsx
  admin-app/components/Movies/coming-soon/edit/edit-dialog.tsx
  admin-app/context/cinema.tsx
  admin-app/context/movie.tsx
  admin-app/types/cinema.ts
  backend-app/src/controller/cinema.ts
  backend-app/src/model/cinema.ts
  backend-app/src/router/cinema.ts
  front-app/src/components/contexts/cinema.tsx
Labels: component, controller, context

#202 zasvaruud
  admin-app/components/Movies/movies/movie-card.tsx
  backend-app/data/cinema.json
  front-app/src/app/ticket/page.tsx
  front-app/src/components/PasswordRecoverPage/ChangeNewPassword/index.tsx
  front-app/src/components/PasswordRecoverPage/EmailInput/index.tsx
  front-app/src/components/PasswordRecoverPage/RecoveryCode/index.tsx
  front-app/src/components/PasswordRecoverPage/index.tsx
  front-app/src/components/app/comingsoon/cardSection.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/app/forgotpassword/index.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/app/ticketpage/index.tsx
  front-app/src/components/app/ticketpage/ticket/dialog.tsx
  front-app/src/components/app/ticketpage/ticket/index.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/ui/select-filter.tsx
Labels: bug, component, context

#204 skeleton nemev
  front-app/src/components/app/comingsoon/cardSection.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/movieCard/index.tsx
Labels: enhancement

#205 unee
  admin-app/components/Cinema/CinemaCard.tsx
  admin-app/components/Cinema/CinemaPut.tsx
  admin-app/components/Cinema/DeleteCinema.tsx
  admin-app/components/Cinema/cinemaBranch.tsx
  admin-app/components/Cinema/dialog-text.tsx
  admin-app/components/Cinema/index.tsx
  admin-app/components/Showtime/index.tsx
  admin-app/components/event/dialog/dialog-text.tsx
  admin-app/components/event/edit/dialog-file.tsx
  admin-app/components/event/edit/dialog-text.tsx
  admin-app/components/event/edit/edit-dialog.tsx
  admin-app/context/auth.tsx
  admin-app/context/cinema.tsx
  admin-app/context/comingsoon.tsx
  admin-app/context/event.tsx
  admin-app/context/passwordrecover.tsx
  admin-app/types/cinema.ts
  backend-app/src/controller/cinema.ts
  backend-app/src/model/cinema.ts
  backend-app/src/router/cinema.ts
  front-app/src/components/carousel/index.tsx
  front-app/src/components/contexts/cinema.tsx
  front-app/src/components/profileDrawer/login.tsx
Labels: bug, component, controller, controllerChange, context

#206 forgotpass loading
  front-app/src/components/PasswordRecoverPage/ChangeNewPassword/index.tsx
  front-app/src/components/PasswordRecoverPage/EmailInput/index.tsx
  front-app/src/components/PasswordRecoverPage/RecoveryCode/index.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/contexts/passwordrecover.tsx
Labels: enhancement

#207 cinema admin
  admin-app/app/cinema/page.tsx
  admin-app/components/Cinema/index.tsx
Labels: bug

#212 refill button
  admin-app/app/profile/page.tsx
  admin-app/app/settings/page.tsx
  admin-app/components/Cinema/dialog-text.tsx
  admin-app/context/cinema.tsx
  admin-app/public/images/cover/cover-02.png
  admin-app/public/images/cover/cover-03.jpeg
  front-app/public/clientqr.png
  front-app/src/components/app/orderPage/paymentQr/index.tsx
  front-app/src/components/footer/index.tsx
Labels: bug, documentation, component, controller

#216 guest button nemev
  admin-app/components/Tables/TableTwo.tsx
  admin-app/context/auth.tsx
  front-app/src/components/app/ticketpage/index.tsx
  front-app/src/components/app/ticketpage/ticket/dialog.tsx
  front-app/src/components/profileDrawer/login.tsx
  front-app/src/components/profileDrawer/signup.tsx
Labels: bug

#217 zasaj duuslaa
  admin-app/components/Movies/coming-soon/edit/edit-dialog.tsx
  admin-app/components/Movies/movies/edit/edit-dialog.tsx
  admin-app/components/event/dialog/dialog-text.tsx
  admin-app/components/event/edit/dialog-file.tsx
  admin-app/components/event/edit/dialog-text.tsx
  admin-app/components/event/edit/edit-dialog.tsx
  admin-app/components/utils/delete/index.tsx
  admin-app/context/event.tsx
  backend-app/src/controller/auth.ts
  backend-app/src/controller/event.ts
  front-app/public/logoLatest.png
  front-app/src/app/favicon.ico
  front-app/src/app/page.tsx
  front-app/src/components/app/comingsoon/cardSection.tsx
  front-app/src/components/app/comingsoon/index.tsx
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/app/icon.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/comingsoon.tsx
  front-app/src/components/contexts/movie.tsx
  front-app/src/components/movieCard/index.tsx
Labels: enhancement

#219 movie card reverse deleted
  front-app/src/components/movieCard/index.tsx
Labels: bug
