Repository Leap-MERN-2023/cinema-app, pull requests merged in 2024-03, with the labels that each got.

#2 project setup
  README.md
Labels: documentation

#15 header
  front-app/package-lock.json
  front-app/package.json
  front-app/public/dune2.avif
  front-app/src/app/layout.tsx
  front-app/src/app/page.tsx
  front-app/src/components/app/carousel/index.tsx
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/app/header/index.tsx
  front-app/tailwind.config.ts
Labels: component

#17 eventsbanner and select-filter
  front-app/package-lock.json
  front-app/package.json
  front-app/src/components/app/dashboard/eventbanner.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/ui/select-filter.tsx
  front-app/styles/global.css
Labels: component

#20 css saijruulalt
  front-app/package-lock.json
  front-app/src/components/app/dashboard/eventbanner.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/ui/select-filter.tsx
Labels: enhancement

#22 margin-20
  front-app/package-lock.json
  front-app/package.json
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/index.ts
  front-app/src/components/movieCard/index.tsx
  front-app/src/components/ui/accordion.tsx
  front-app/src/components/ui/alert-dialog.tsx
  front-app/src/components/ui/alert.tsx
  front-app/src/components/ui/aspect-ratio.tsx
  front-app/src/components/ui/avatar.tsx
  front-app/src/components/ui/breadcrumb.tsx
  front-app/src/components/ui/button.tsx
  front-app/src/components/ui/calendar.tsx
  front-app/src/components/ui/checkbox.tsx
  front-app/src/components/ui/collapsible.tsx
  front-app/src/components/ui/command.tsx
  front-app/src/components/ui/context-menu.tsx
  front-app/src/components/ui/dialog.tsx
  front-app/src/components/ui/drawer.tsx
  front-app/src/components/ui/dropdown-menu.tsx
  front-app/src/components/ui/form.tsx
  front-app/src/components/ui/hover-card.tsx
  front-app/src/components/ui/input-otp.tsx
  front-app/src/components/ui/input.tsx
  front-app/src/components/ui/label.tsx
  front-app/src/components/ui/menubar.tsx
  front-app/src/components/ui/navigation-menu.tsx
  front-app/src/components/ui/pagination.tsx
  front-app/src/components/ui/popover.tsx
  front-app/src/components/ui/progress.tsx
  front-app/src/components/ui/radio-group.tsx
  front-app/src/components/ui/resizable.tsx
  front-app/src/components/ui/scroll-area.tsx
  front-app/src/components/ui/select.tsx
  front-app/src/components/ui/separator.tsx
  front-app/src/components/ui/sheet.tsx
  front-app/src/components/ui/skeleton.tsx
  front-app/src/components/ui/slider.tsx
  front-app/src/components/ui/sonner.tsx
  front-app/src/components/ui/switch.tsx
  front-app/src/components/ui/table.tsx
  front-app/src/components/ui/tabs.tsx
  front-app/src/components/ui/textarea.tsx
  front-app/src/components/ui/toast.tsx
  front-app/src/components/ui/toaster.tsx
  front-app/src/components/ui/toggle-group.tsx
  front-app/src/components/ui/toggle.tsx
  front-app/src/components/ui/tooltip.tsx
  front-app/src/components/ui/use-toast.ts
Labels: enhancement

#23 12 movie card component
  front-app/package-lock.json
Labels: bug

#26 footer
  backend-app/src/index.ts
  front-app/package-lock.json
  front-app/public/qr/Untitled.svg
  front-app/src/app/layout.tsx
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/footer/index.tsx
  front-app/src/components/header/index.tsx
  front-app/src/components/index.ts
  front-app/src/components/movieCard/index.tsx
  package-lock.json
Labels: component

#27 header duuslaa
  front-app/package-lock.json
  front-app/src/components/header/index.tsx
Labels: component

#28 12 movie card component
  front-app/package-lock.json
  front-app/src/app/layout.tsx
  front-app/src/components/movieCard/cards.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/movieCard/index.tsx
Labels: enhancement

#29 12 movie card component
  front-app/src/app/layout.tsx
  front-app/src/components/movieCard/index.tsx
Labels: bug

#30 12 movie card component
  front-app/src/components/movieCard/index.tsx
Labels: bug

#32 profileDrawer
  front-app/package-lock.json
  front-app/package.json
  front-app/src/app/layout.tsx
  front-app/src/components/app/dashboard/eventbanner.tsx
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/header/index.tsx
  front-app/src/components/index.ts
  front-app/src/components/profileDrawer/index.tsx
  front-app/src/components/ui/passwordinput.tsx
  package-lock.json
Labels: component

#33 event page
  front-app/src/app/event/page.tsx
  front-app/src/components/app/event/data.ts
  front-app/src/components/app/event/index.tsx
  front-app/src/components/app/index.ts
  front-app/src/components/footer/index.tsx
Labels: page

#36 ticket-page
  front-app/package-lock.json
  front-app/src/app/ticket/page.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/app/ticketpage/index.tsx
  front-app/src/components/index.ts
  front-app/src/components/ticket/index.tsx
Labels: component

#37 12 movie card component
  front-app/src/components/index.ts
  front-app/src/components/movieCard/card.tsx
  front-app/src/components/movieCard/cards.tsx
  front-app/src/components/movieCard/cinemas.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/movieCard/index.tsx
Labels: component

#38 12 movie card component
  front-app/src/components/movieCard/dialog.tsx
Labels: enhancement, component

#40 coming-soon-modal
  front-app/src/components/app/comingsoon/cardSection.tsx
  front-app/src/components/app/comingsoon/cards.tsx
  front-app/src/components/app/comingsoon/cinemas.tsx
  front-app/src/components/app/comingsoon/comingModal.tsx
  front-app/src/components/app/comingsoon/resizeImage.tsx
Labels: component

#47 404 page
  front-app/src/app/not-found.tsx
Labels: page

#52 paymentqr
  .DS_Store
  front-app/src/components/app/orderPage/paymentQr/index.tsx
Labels: component

#55 TicketInfo component
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/app/orderPage/ticketInfo/index.tsx
  front-app/src/components/carousel/index.tsx
Labels: component

#56 checkout
  front-app/public/banklogos/khaanbank.png
  front-app/public/banklogos/khasbank.png
  front-app/public/banklogos/socialpay.png
  front-app/public/banklogos/tdb.png
  front-app/src/components/app/orderPage/checkout/form.tsx
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/index.tsx
Labels: component

#59 footer responsive
  front-app/src/components/footer/index.tsx
Labels: enhancement

#61 checkout button zasav
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/index.tsx
Labels: bug

#64 49 seat component
  backend-app/src/config/index.ts
  backend-app/src/controller/movie.ts
  backend-app/src/index.ts
  backend-app/src/middleware/errorHandler.ts
  backend-app/src/model/movie.ts
  backend-app/src/router/movie.ts
  backend-app/src/utils/myError.ts
  front-app/public/banklogos/khaanbank.png
  front-app/public/banklogos/khasbank.png
  front-app/public/banklogos/socialpay.png
  front-app/public/banklogos/tdb.png
  front-app/src/components/app/orderPage/checkout/form.tsx
  front-app/src/components/app/orderPage/orderParts/seats.tsx
Labels: component

#65 49 seat component
  front-app/public/banklogos/khaanbank.png
  front-app/public/banklogos/khasbank.png
  front-app/public/banklogos/socialpay.png
  front-app/public/banklogos/tdb.png
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/footer/index.tsx
  front-app/src/components/movieCard/cinemas.tsx
Labels: component

#67 backend src file
  backend-app/src/config/index.ts
  backend-app/src/controller/movie.ts
  backend-app/src/index.ts
  backend-app/src/middleware/errorHandler.ts
  backend-app/src/model/movie.ts
  backend-app/src/router/movie.ts
  backend-app/src/utils/myError.ts
Labels: bug

#68 50 checkout component
  backend-app/package-lock.json
  backend-app/package.json
  backend-app/src/config/db.ts
  backend-app/src/index.ts
Labels: component

#73 final footer
  front-app/src/components/footer/index.tsx
Labels: enhancement

#75 buh model duusagsaa
  backend-app/src/index.ts
  backend-app/src/model/cinema.ts
  backend-app/src/model/customer.ts
  backend-app/src/model/movie.ts
  backend-app/src/model/order.ts
  backend-app/src/model/screen.ts
  backend-app/src/model/seat.ts
  backend-app/src/model/showtime.ts
  backend-app/src/model/ticket.ts
Labels: enhancement

#76 mongoruu holbood get create movie huselt bichlee
  backend-app/package-lock.json
  backend-app/package.json
  backend-app/src/controller/movie.ts
  backend-app/src/controller/seat.ts
  backend-app/src/index.ts
  backend-app/src/model/movie.ts
  backend-app/src/router/movie.ts
  backend-app/src/router/seat.ts
  backend-app/src/utils/myError.ts
  backend-app/tsconfig.json
Labels: controller

#78 request amjilttai
  .gitignore
  backend-app/src/controller/cinema.ts
  backend-app/src/index.ts
  backend-app/src/router/cinema.ts
Labels: component

#80 screen request amjilttai
  backend-app/src/controller/screen.ts
  backend-app/src/index.ts
  backend-app/src/router/screen.ts
Labels: component

#84 ticket uusgelee
  backend-app/src/controller/ticket.ts
Labels: controller

#87 cinema.json
  backend-app/data/cinema.json
  backend-app/src/utils/cinema.ts
Labels: enhancement

#88 79 screen request
  backend-app/data/cinema.json
  backend-app/package.json
  backend-app/src/model/cinema.ts
  backend-app/src/utils/cinema.ts
Labels: bug

#89 ticket controller zasav
  backend-app/src/index.ts
  backend-app/src/router/ticket.ts
Labels: controllerChange

#90 dash
  front-app/src/components/app/dashboard/eventbanner.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/carousel/dialog.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/header/index.tsx
  front-app/src/components/movieCard/card.tsx
  front-app/src/components/movieCard/cards.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/movieCard/index.tsx
  front-app/src/components/profileDrawer/index.tsx
  front-app/src/components/ui/select-filter.tsx
Labels: enhancement

#91 85 customer backend and order backend
  backend-app/src/controller/order.ts
  backend-app/src/index.ts
  backend-app/src/middleware/auth.ts
  backend-app/src/model/order.ts
  backend-app/src/router/auth.ts
  backend-app/src/router/order.ts
  backend-app/src/utils/interface.ts
Labels: controller

#94 authContext
  backend-app/data/film.json
  backend-app/src/controller/showtime.ts
  backend-app/src/model/showtime.ts
  front-app/package.json
  front-app/src/app/layout.tsx
  front-app/src/components/app/comingsoon/cardSection.tsx
  front-app/src/components/app/comingsoon/index.tsx
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/app/orderPage/cinema/cinema.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/app/orderPage/orderParts/index.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/index.ts
  front-app/src/components/header/index.tsx
  front-app/src/components/index.ts
  front-app/src/components/profileDrawer/index.tsx
  front-app/src/components/profileDrawer/login.tsx
  front-app/src/components/profileDrawer/signup.tsx
  front-app/src/components/utils/axios.ts
Labels: component

#102 carousel cinema
  backend-app/data/cinema.json
  backend-app/src/model/cinema.ts
  front-app/public/prime-cineplex-1.png
  front-app/public/prime-cineplex-2.png
  front-app/public/prime-cineplex-3.png
  front-app/src/app/layout.tsx
  front-app/src/components/app/orderPage/cinema/cinemaButton.tsx
  front-app/src/components/app/orderPage/cinema/cinemaSection.tsx
  front-app/src/components/app/orderPage/cinema/index.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/contexts/cinema.tsx
  front-app/src/components/contexts/index.ts
Labels: context

#103 movie card backendtei holbov
  front-app/package-lock.json
  front-app/package.json
  front-app/src/components/movieCard/card.tsx
  front-app/src/components/movieCard/cards.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/movieCard/index.tsx
  front-app/src/components/movieCard/resizeImage.tsx
Labels: duplicate, enhancement

#104 95 screen context
  backend-app/data/seat.json
  backend-app/package.json
  backend-app/src/controller/screen.ts
  backend-app/src/controller/seat.ts
  backend-app/src/model/screen.ts
  backend-app/src/model/seat.ts
  backend-app/src/router/screen.ts
  backend-app/src/utils/seats.ts
  front-app/src/app/layout.tsx
  front-app/src/components/app/orderPage/orderParts/seats.tsx
  front-app/src/components/contexts/screen.tsx
Labels: context

#107 profile hiilee
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/profileDrawer/index.tsx
  front-app/src/components/profileDrawer/login.tsx
  front-app/src/components/profileDrawer/profile.tsx
  front-app/src/components/profileDrawer/signup.tsx
Labels: component

#109 95 screen context
  backend-app/src/controller/screen.ts
  backend-app/src/model/screen.ts
  backend-app/src/router/screen.ts
  front-app/src/components/app/orderPage/orderParts/seats.tsx
Labels: context

#111 zunduu l olon ym hiileedee
  backend-app/data/film.json
  front-app/src/components/app/comingsoon/comingModal.tsx
  front-app/src/components/app/dashboard/eventbanner.tsx
  front-app/src/components/app/dashboard/filterSection.tsx
  front-app/src/components/app/dashboard/index.tsx
  front-app/src/components/app/orderPage/cinema/index.tsx
  front-app/src/components/carousel/dialog.tsx
  front-app/src/components/carousel/image.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/contexts/cinema.tsx
  front-app/src/components/contexts/movie.tsx
  front-app/src/components/header/index.tsx
  front-app/src/components/movieCard/card.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/ui/select-filter.tsx
Labels: documentation, component, context

#112 checkout movie gargav order huselt hiiv
  backend-app/src/model/order.ts
  front-app/src/app/layout.tsx
  front-app/src/components/app/orderPage/checkout/index.tsx
  front-app/src/components/contexts/auth.tsx
  front-app/src/components/contexts/index.ts
  front-app/src/components/contexts/movie.tsx
  front-app/src/components/contexts/order.tsx
  front-app/src/components/movieCard/dialog.tsx
  front-app/src/components/profileDrawer/index.tsx
Labels: component, controller, context

#114 carouseliin trailer bolson
  front-app/src/components/carousel/dialog.tsx
  front-app/src/components/carousel/index.tsx
  front-app/src/components/carousel/trailerModal.tsx
Labels: component, context

#115 dfone
  backend-app/data/showtime.json
  backend-app/package.json
  backend-app/src/controller/showtime.ts
  backend-app/src/model/showtime.ts
  backend-app/src/utils/showtime.ts
  front-app/src/app/layout.tsx
  front-app/src/components/app/orderPage/cinema/cinemaButton.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/showtime.tsx
Labels: component

#119 seats ordertoi barag holbov
  backend-app/src/controller/showtime.ts
  backend-app/src/router/showtime.ts
  front-app/src/components/app/orderPage/orderParts/index.tsx
  front-app/src/components/app/orderPage/orderParts/seats.tsx
  front-app/src/components/app/orderPage/orderParts/ticketInfo/index.tsx
  front-app/src/components/contexts/showtime.tsx
Labels: context

#120 order bolson bho
  front-app/src/app/order/page.tsx
  front-app/src/components/app/orderPage/index.tsx
  front-app/src/components/carousel/index.tsx
Labels: component
